version: "3.9"

services:
  database:
    image: postgres:12-alpine
    network_mode: "host"
    environment:
      POSTGRES_DB: benchmark
      POSTGRES_USER: bench_user
      POSTGRES_PASSWORD: bench_pass
    volumes:
      - ./tests/src/test/resources/create_database.sql:/docker-entrypoint-initdb.d/init.sql

  benchmark-spring:
    image: gr3gdev/benchmark-spring
    network_mode: "host"
    ports:
      - 9001:9001
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 650M
        reservations:
          cpus: '0.50'
          memory: 512M
    depends_on:
      database:
        condition: service_healthy

  benchmark-quarkus:
    image: gr3gdev/benchmark-quarkus
    network_mode: "host"
    ports:
      - 9002:9002
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 650M
        reservations:
          cpus: '0.50'
          memory: 512M
    depends_on:
      database:
        condition: service_healthy

  benchmark-fenrir:
    image: gr3gdev/benchmark-fenrir
    network_mode: "host"
    ports:
      - 9003:9003
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 650M
        reservations:
          cpus: '0.50'
          memory: 512M
    depends_on:
      database:
        condition: service_healthy
