version: "3.3"

services:
  benchmark-spring:
    image: gr3gdev/benchmark-spring
    ports:
      - 9001:9001

  benchmark-quarkus:
    image: gr3gdev/benchmark-quarkus
    ports:
      - 9002:9002

  benchmark-fenrir:
    image: gr3gdev/benchmark-fenrir
    ports:
      - 9003:9003
