[versions]
lombok = "1.18.30"
fenrir = "0.1.0"

[libraries]
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
fenrir-api = { module = "io.github.gr3gdev:fenrir-api", version.ref = "fenrir" }
fenrir-http = { module = "io.github.gr3gdev:fenrir-http", version.ref = "fenrir" }
fenrir-rest = { module = "io.github.gr3gdev:fenrir-rest", version.ref = "fenrir" }
fenrir-jpa = { module = "io.github.gr3gdev:fenrir-jpa", version.ref = "fenrir" }
