version: "3.9"

services:
  db-jpa:
    image: postgres:12-alpine
    environment:
      POSTGRES_DB: jpa
      POSTGRES_USER: smpl_jpa_user
      POSTGRES_PASSWORD: smpl_jpa_pass
    ports:
      - 54320:5432
    volumes:
      - ./common/common-jpa/create_database.sql:/docker-entrypoint-initdb.d/init.sql

  db-thymeleaf:
    image: postgres:12-alpine
    environment:
      POSTGRES_DB: thymeleaf
      POSTGRES_USER: smpl_thymeleaf_user
      POSTGRES_PASSWORD: smpl_thymeleaf_pass
    ports:
      - 54321:5432
    volumes:
      - ./common/common-thymeleaf/create_database.sql:/docker-entrypoint-initdb.d/init.sql
