# JDK image
FROM alpine as base
RUN apk add --update openjdk[javaVersion] binutils

# Optimize JRE
FROM base as customjre
COPY ./deps.info /work/deps.info
WORKDIR /work

# create a custom jre
RUN jlink \
    --add-modules $(cat deps.info) \
    --strip-debug \
    --compress 2 \
    --no-header-files \
    --no-man-pages \
    --output customjre

# Slim image
FROM alpine
ENV JAVA_HOME /jre
ENV JAVA_OPTS "-Xms256m -Xmx256m -Xss512k"
ENV PATH $JAVA_HOME/bin:$PATH
RUN mkdir /libs
COPY --from=customjre /work/customjre $JAVA_HOME
COPY ./libs /libs
COPY ./entrypoint.sh /bin/entrypoint

RUN chmod +x /bin/entrypoint

ENTRYPOINT [ "/bin/entrypoint" ]
CMD ["sh", "-c", "java ${JAVA_OPTS} -cp /libs/ [mainClass]"]
